# Generated by Django 5.1.4 on 2024-12-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Host_Admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomAdmin',
        ),
    ]
