# Generated by Django 5.1.4 on 2024-12-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Host_Admin', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
