# Generated by Django 5.1.4 on 2025-01-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Host_Admin', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
