# Generated by Django 5.1.5 on 2025-01-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddToCard',
        ),
    ]
