from .admin_views import admin_home,admin_login,logout_view
from .product_views import add_product,admin_product_list,delete_product,update_product
from .order_views import create_order,order_detail,update_order_status,vieworders